name = "seo-meta-generator"
main = "worker.js"
compatibility_date = "2025-08-07"

# When deploying to your own account, set your account_id here or as an environment variable.
# account_id = "YOUR_ACCOUNT_ID"

[vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"